name: icon_set_generator
description: A CLI tool to help generate sets of icons for new applications.
version: 1.0.0
homepage: https://github.com/POWRFULCOW89/icon_set_generator

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  args: ^2.3.0
  image: ^3.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
