name: icon_set_generator
description: A CLI tool to help generate sets of icons for applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  args: ^2.3.0
  image: ^3.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
